### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Teicu** [ptonewreckin/BlindRef#1]
Hi 

can you help me please fix this error 

Traceback (most recent call last):
  File "./BlindRef_Attacker.py", line 3, in <module>
    import requests, re, sys, getopt, json, urllib2, copy
ImportError: No module named requests 

Thank you very much

**Comment by Teicu** [comment]
and using python3 I get another error 

 python3 ./BlindRef_Attacker.py -s http://myip -p 8080 -r sampleRequest.py
  File "./BlindRef_Attacker.py", line 48
    print 'BlindRef_Attacker.py -s serverURL -p serverPort -r webRequest'
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('BlindRef_Attacker.py -s serverURL -p serverPort -r webRequest')?

**Comment by ptonewreckin** [comment]
Hi @Teicu, try installing requests.... pip install requests --user
